services:
  mysql:
    image: mysql:8.0.36
    container_name: employee_market_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3335:3306"
    volumes:
      #      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/employee_market_data:/var/lib/mysql