spring:
  application:
    name: coupon_market_service
  datasource:
    name: coupon_service
    url: jdbc:mysql://localhost:3332/coupon_market_service
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
    ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/supermarket-management-system
          jwk-set-uri: http://localhost:8181/realms/supermarket-management-system/protocol/openid-connect/certs
server:
  port: 8081
