spring:
  application:
    name: employee_market_service
  datasource:
    name: employee_service
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
    ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI}
server:
  port: 8084
keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  realm: supermarket-management-system
  resource: react-backend
  credentials:
    secret: ${KEYCLOAK_SECRET}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}
    client-id: admin-cli

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
